-- =============================================================================
-- Run all Lib tests
-- =============================================================================
-- Usage: lua tests/all.lua (from the adamant-modpack-Lib directory)

require('tests/TestMainBoot')
require('tests/TestLogging')
require('tests/TestValues')
require('tests/TestGameDeps')
require('tests/TestSystemScope')
require('tests/TestStorageValidation')
require('tests/TestHashing')
require('tests/TestModuleState_DataDefaults')
require('tests/TestModuleState_PersistentState')
require('tests/TestModuleState_StagedState')
require('tests/TestCache')
require('tests/TestControls')
require('tests/TestCoordinator')
require('tests/TestShared')
require('tests/TestHooks')
require('tests/TestOverlays')
require('tests/TestOverlays_Retained')
require('tests/TestMutation_BackupSystem')
require('tests/TestMutation_DefinitionLifecycle')
require('tests/TestMutation')
require('tests/TestManagedModule')
require('tests/TestModuleDefinitionContract')
require('tests/TestCreateModule')
require('tests/TestManagedModule_PrepareDefinition')
require('tests/TestManagedModule_IsEnabled')
require('tests/TestFallbackUi')
require('tests/TestPhaseGate')
require('tests/TestWidgets')
require('tests/TestWidgets_Nav')

local lu = require('luaunit')
os.exit(lu.LuaUnit.run())
